import { paginationOptsValidator } from "convex/server";
import { v } from "convex/values";
import { query, mutation } from "./_generated/server";
import { getAuthUserId } from "@convex-dev/auth/server";

const ACTIVE_EXPERIMENT = "am-vs-am2-v2";
const variantValidator = v.union(v.literal("AM"), v.literal("AM2"));
const statusValidator = v.union(v.literal("INITIATED"), v.literal("PENDING"), v.literal("COMPLETED"), v.literal("FAILED"), v.literal("UNKNOWN"));
const entryValidator = v.union(v.literal("randomized"), v.literal("direct"), v.literal("test"));
const filterValidator = v.object({
  startAt: v.optional(v.number()), endAt: v.optional(v.number()), variant: v.optional(variantValidator), entryType: v.optional(entryValidator),
  utmSource: v.optional(v.string()), utmMedium: v.optional(v.string()), utmCampaign: v.optional(v.string()), utmContent: v.optional(v.string()), utmTerm: v.optional(v.string()), utmId: v.optional(v.string()),
});

export const getExperiment = query({ args: {}, returns: v.any(), handler: async (ctx) => { await requireAdmin(ctx); const row = await ctx.db.query("experiments").withIndex("by_experiment_id", (q) => q.eq("experimentId", ACTIVE_EXPERIMENT)).unique(); return row ? pickExperiment(row) : { experimentId: ACTIVE_EXPERIMENT, enabled: false, amPercentage: 50, am2Percentage: 50 }; } });

export const getOverview = query({ args: { filters: filterValidator }, returns: v.any(), handler: async (ctx, { filters }) => { await requireAdmin(ctx); const [orders, exposures, checkouts] = await Promise.all([loadOrders(ctx, filters, 10000), loadRows(ctx, "exposures", filters), loadRows(ctx, "checkoutVisits", filters)]); return { ...buildOverview(orders, exposures, checkouts), generatedAt: Date.now(), sourceLimitReached: orders.length >= 10000 || exposures.length >= 10000 || checkouts.length >= 10000 }; } });

export const listOrders = query({ args: { limit: v.optional(v.number()), status: v.optional(statusValidator), search: v.optional(v.string()), filters: v.optional(filterValidator) }, returns: v.array(v.any()), handler: async (ctx, args) => { await requireAdmin(ctx); return loadOrders(ctx, { ...(args.filters || {}), status: args.status, search: args.search }, Math.min(args.limit || 50, 200)); } });

export const listOrdersPage = query({ args: { paginationOpts: paginationOptsValidator, status: v.optional(statusValidator), search: v.optional(v.string()), filters: v.optional(filterValidator) }, returns: v.any(), handler: async (ctx, args) => { await requireAdmin(ctx); const filters = { ...(args.filters || {}), status: args.status, search: args.search }; const base = args.status ? ctx.db.query("orders").withIndex("by_state", (q) => q.eq("state", args.status!)) : ctx.db.query("orders").withIndex("by_created_at"); const paged = await base.order("desc").paginate(args.paginationOpts); return { ...paged, page: paged.page.filter((row) => matchesOrder(row, filters)) }; } });

export const getOrder = query({ args: { merchantOrderId: v.string() }, returns: v.any(), handler: async (ctx, { merchantOrderId }) => { await requireAdmin(ctx); const order = await ctx.db.query("orders").withIndex("by_merchant_order_id", (q) => q.eq("merchantOrderId", merchantOrderId)).unique(); if (!order) return null; const receipts = await ctx.db.query("paymentReceipts").withIndex("by_order", (q) => q.eq("merchantOrderId", merchantOrderId)).order("desc").take(50); return { ...order, receipts }; } });

export const getContacts = query({ args: { search: v.optional(v.string()), paginationOpts: paginationOptsValidator }, returns: v.any(), handler: async (ctx, args) => { await requireAdmin(ctx); const base = args.search ? ctx.db.query("contacts").withSearchIndex("search_name", (q) => q.search("name", args.search!)) : ctx.db.query("contacts").withIndex("by_last_seen"); return base.paginate(args.paginationOpts); } });

export const getCampaigns = query({ args: { filters: filterValidator }, returns: v.array(v.any()), handler: async (ctx, { filters }) => { await requireAdmin(ctx); const [exposures, checkouts, orders] = await Promise.all([loadRows(ctx, "exposures", filters), loadRows(ctx, "checkoutVisits", filters), loadOrders(ctx, filters, 10000)]); const groups = new Map(); for (const row of [...exposures, ...checkouts.map((item: any) => ({ ...item, kind: "checkout" }))]) { const key = campaignKey(row); const group = groups.get(key) || emptyCampaign(row); if (row.kind === "checkout") group.checkoutVisitors.add(row.visitorId); else group.visitors.add(row.visitorId); groups.set(key, group); } for (const order of orders) { const row = order.attribution || order; const key = campaignKey(row); const group = groups.get(key) || emptyCampaign(row); group.initiated += 1; if (order.state === "PENDING") group.pending += 1; if (order.state === "FAILED") group.failed += 1; if (order.state === "COMPLETED") { group.paid += 1; group.revenuePaise += order.amountPaise; } groups.set(key, group); } return [...groups.values()].map(serializeCampaign).sort((a, b) => b.revenuePaise - a.revenuePaise); } });

export const getFunnel = query({ args: { filters: filterValidator }, returns: v.any(), handler: async (ctx, { filters }) => { await requireAdmin(ctx); const [landings, checkouts, orders] = await Promise.all([loadRows(ctx, "exposures", filters), loadRows(ctx, "checkoutVisits", filters), loadOrders(ctx, filters, 10000)]); const stages = [new Set(landings.map((row: any) => row.visitorId)), new Set(checkouts.map((row: any) => row.visitorId)), new Set(orders.map((row: any) => row.visitorId).filter(Boolean)), new Set(orders.filter((row: any) => row.state === "COMPLETED").map((row: any) => row.visitorId).filter(Boolean))]; const labels = ["Recorded landing", "Checkout visited", "Payment initiated", "Confirmed purchase"]; return labels.map((label, index) => ({ label, count: stages[index].size, conversion: index ? percentage(stages[index].size, stages[index - 1].size) : 100, dropoff: index ? Math.max(0, stages[index - 1].size - stages[index].size) : 0 })); } });

export const getHealth = query({ args: {}, returns: v.any(), handler: async (ctx) => { await requireAdmin(ctx); const pending = await ctx.db.query("orders").withIndex("by_state", (q) => q.eq("state", "PENDING")).order("desc").take(1000); const orders = await ctx.db.query("orders").withIndex("by_created_at").order("desc").take(2000); const receipts = await ctx.db.query("paymentReceipts").withIndex("by_order").order("desc").take(1000); const failures = await ctx.db.query("reportingFailures").withIndex("by_kind").order("desc").take(1000); const orderIds = new Set(orders.map((row: any) => row.merchantOrderId)); return { stalePending: pending.filter((row: any) => Date.now() - row.createdAt > 24 * 60 * 60 * 1000).length, unmatchedReceipts: receipts.filter((row: any) => !orderIds.has(row.merchantOrderId)).length, reportingFailures: failures.filter((row: any) => !row.resolvedAt).length, lastReceiptAt: receipts[0]?.receivedAt || 0, lastOrderAt: orders[0]?.updatedAt || 0, recentFailures: failures.filter((row: any) => !row.resolvedAt).slice(0, 20) }; } });

export const updateExperiment = mutation({ args: { enabled: v.optional(v.boolean()), amPercentage: v.optional(v.number()), am2Percentage: v.optional(v.number()) }, returns: v.object({ updated: v.boolean() }), handler: async (ctx, args) => { const actorUserId = await requireAdmin(ctx); const existing = await ctx.db.query("experiments").withIndex("by_experiment_id", (q) => q.eq("experimentId", ACTIVE_EXPERIMENT)).unique(); const amPercentage = args.amPercentage ?? existing?.amPercentage ?? 50; const am2Percentage = args.am2Percentage ?? existing?.am2Percentage ?? 100 - amPercentage; if (amPercentage < 0 || amPercentage > 100 || am2Percentage < 0 || am2Percentage > 100 || amPercentage + am2Percentage !== 100) throw new Error("Allocation must total 100%."); const now = Date.now(); if (existing) await ctx.db.patch(existing._id, { enabled: args.enabled ?? existing.enabled, amPercentage, am2Percentage, updatedAt: now }); else await ctx.db.insert("experiments", { experimentId: ACTIVE_EXPERIMENT, enabled: args.enabled ?? false, amPercentage, am2Percentage, createdAt: now, updatedAt: now }); await ctx.db.insert("adminAudit", { action: "experiment.update", actorUserId, details: JSON.stringify({ enabled: args.enabled, amPercentage, am2Percentage }), occurredAt: now }); return { updated: true }; } });

async function loadRows(ctx: any, table: "exposures" | "checkoutVisits", filters: any) { const base = table === "exposures" ? ctx.db.query(table).withIndex("by_experiment_variant", (q: any) => q.eq("experimentId", ACTIVE_EXPERIMENT)) : ctx.db.query(table).withIndex("by_occurred_at"); return (await base.order("desc").take(10000)).filter((row: any) => inRange(row.occurredAt, filters) && matchesAttribution(row, filters)); }
async function loadOrders(ctx: any, filters: any, limit: number) { const base = filters.status ? ctx.db.query("orders").withIndex("by_state", (q: any) => q.eq("state", filters.status)) : ctx.db.query("orders").withIndex("by_created_at"); return (await base.order("desc").take(limit)).filter((row: any) => matchesOrder(row, filters)); }
function buildOverview(orders: any[], exposures: any[], checkouts: any[]) { const paid = orders.filter((row) => row.state === "COMPLETED"); const purchasers = new Set(paid.map((row) => row.visitorId).filter(Boolean)); const byVariant: any = { AM: emptyVariant(), AM2: emptyVariant() }; exposures.forEach((row) => { if (byVariant[row.variant]) byVariant[row.variant].visitors += 1; }); paid.forEach((order) => { const target = byVariant[order.variant]; if (!target) return; target.paidOrders += 1; target.revenuePaise += order.amountPaise; if (order.visitorId) target.purchasingVisitors.add(order.visitorId); }); Object.values(byVariant).forEach((row: any) => { row.purchasingVisitors = row.purchasingVisitors instanceof Set ? row.purchasingVisitors.size : row.purchasingVisitors; row.conversionRate = percentage(row.purchasingVisitors, row.visitors); }); const revenuePaise = paid.reduce((sum, row) => sum + row.amountPaise, 0); return { visitors: exposures.length, checkoutVisitors: new Set(checkouts.map((row) => row.visitorId)).size, initiatedOrders: orders.length, pendingOrders: orders.filter((row) => row.state === "PENDING").length, failedOrders: orders.filter((row) => row.state === "FAILED").length, unknownOrders: orders.filter((row) => row.state === "UNKNOWN").length, paidOrders: paid.length, purchasingVisitors: purchasers.size, conversionRate: percentage(purchasers.size, exposures.length), revenuePaise, averageOrderValuePaise: paid.length ? Math.round(revenuePaise / paid.length) : 0, revenuePerVisitorPaise: exposures.length ? Math.round(revenuePaise / exposures.length) : 0, byVariant }; }
function emptyVariant() { return { visitors: 0, purchasingVisitors: new Set(), paidOrders: 0, revenuePaise: 0 }; }
function emptyCampaign(row: any = {}) { return { key: campaignKey(row), source: row.utmSource || "Not recorded", medium: row.utmMedium || "Not recorded", campaign: row.utmCampaign || "Not recorded", visitors: new Set(), checkoutVisitors: new Set(), initiated: 0, pending: 0, failed: 0, paid: 0, revenuePaise: 0 }; }
function serializeCampaign(row: any) { return { ...row, visitors: row.visitors.size, checkoutVisitors: row.checkoutVisitors.size, conversionRate: percentage(row.paid, row.visitors.size) }; }
function campaignKey(row: any = {}) { return [row.utmSource || "", row.utmMedium || "", row.utmCampaign || "", row.utmContent || "", row.utmId || ""].join("|") || "not-recorded"; }
function matchesOrder(row: any, filters: any = {}) { return inRange(row.createdAt, filters) && matchesAttribution(row.attribution || row, filters) && (!filters.search || [row.merchantOrderId, row.customerName, row.customerEmail, row.customerPhone].some((value) => String(value || "").toLowerCase().includes(String(filters.search).toLowerCase()))); }
function matchesAttribution(row: any, filters: any = {}) { const fields = ["utmSource", "utmMedium", "utmCampaign", "utmContent", "utmTerm", "utmId"]; if (filters.variant && row.variant !== filters.variant) return false; if (filters.entryType && row.entryType !== filters.entryType) return false; return fields.every((field) => !filters[field] || row[field] === filters[field]); }
function inRange(timestamp: number, filters: any = {}) { return (!filters.startAt || timestamp >= filters.startAt) && (!filters.endAt || timestamp < filters.endAt); }
function percentage(numerator: number, denominator: number) { return denominator ? Number(((numerator / denominator) * 100).toFixed(2)) : 0; }
function pickExperiment(row: any) { return { experimentId: row.experimentId, enabled: row.enabled, amPercentage: row.amPercentage, am2Percentage: row.am2Percentage }; }
async function requireAdmin(ctx: any) { const userId = await getAuthUserId(ctx); if (!userId) throw new Error("Unauthenticated"); const user = await ctx.db.get(userId); const allowed = String(process.env.ADMIN_EMAIL || "").trim().toLowerCase(); if (!user?.email || !allowed || user.email.toLowerCase() !== allowed) throw new Error("Forbidden"); return userId; }
