import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

const attributionFields = {
  experimentId: v.string(),
  visitorId: v.string(),
  variant: v.union(v.literal("AM"), v.literal("AM2")),
  entryType: v.union(v.literal("randomized"), v.literal("direct"), v.literal("test")),
  utmSource: v.optional(v.string()),
  utmMedium: v.optional(v.string()),
  utmCampaign: v.optional(v.string()),
  utmContent: v.optional(v.string()),
  utmTerm: v.optional(v.string()),
  utmId: v.optional(v.string()),
  gclid: v.optional(v.string()),
  gbraid: v.optional(v.string()),
  wbraid: v.optional(v.string()),
  fbclid: v.optional(v.string()),
};

export default defineSchema({
  ...authTables,
  experiments: defineTable({ experimentId: v.string(), enabled: v.boolean(), amPercentage: v.number(), am2Percentage: v.number(), createdAt: v.number(), updatedAt: v.number() }).index("by_experiment_id", ["experimentId"]),
  exposures: defineTable({ ...attributionFields, dedupeKey: v.string(), occurredAt: v.number() }).index("by_dedupe_key", ["dedupeKey"]).index("by_experiment_variant", ["experimentId", "variant", "occurredAt"]).index("by_occurred_at", ["occurredAt"]),
  checkoutVisits: defineTable({ ...attributionFields, dedupeKey: v.optional(v.string()), occurredAt: v.number(), eventType: v.optional(v.union(v.literal("checkout_visit"), v.literal("checkout_submit"), v.literal("thankyou_visit"))) }).index("by_visitor", ["visitorId", "occurredAt"]).index("by_dedupe_key", ["dedupeKey"]).index("by_occurred_at", ["occurredAt"]),
  orders: defineTable({
    merchantOrderId: v.string(),
    amountPaise: v.number(),
    state: v.union(v.literal("INITIATED"), v.literal("PENDING"), v.literal("COMPLETED"), v.literal("FAILED"), v.literal("UNKNOWN")),
    visitorId: v.optional(v.string()),
    variant: v.optional(v.union(v.literal("AM"), v.literal("AM2"))),
    entryType: v.optional(v.union(v.literal("randomized"), v.literal("direct"), v.literal("test"))),
    attribution: v.optional(v.object(attributionFields)),
    customerName: v.optional(v.string()),
    customerEmail: v.optional(v.string()),
    customerPhone: v.optional(v.string()),
    selectedAddons: v.optional(v.array(v.string())),
    lineItems: v.optional(v.array(v.object({ id: v.string(), title: v.string(), pricePaise: v.number() }))),
    failureType: v.optional(v.union(v.literal("payment_failed"), v.literal("checkout_error"), v.literal("provider_uncertain"), v.literal("reporting_failure"))),
    failureCode: v.optional(v.string()),
    failureMessage: v.optional(v.string()),
    lastProviderCheckAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    paymentTimeline: v.optional(v.array(v.object({ state: v.string(), occurredAt: v.number(), providerEventId: v.optional(v.string()), message: v.optional(v.string()) }))),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_merchant_order_id", ["merchantOrderId"]).index("by_state", ["state", "updatedAt"]).index("by_visitor_state", ["visitorId", "state"]).index("by_created_at", ["createdAt"]).index("by_customer_email", ["customerEmail"]).index("by_customer_phone", ["customerPhone"]).searchIndex("search_customer_name", { searchField: "customerName", filterFields: ["state"] }),
  contacts: defineTable({ email: v.string(), normalizedEmail: v.string(), name: v.string(), phone: v.string(), firstSeenAt: v.number(), lastSeenAt: v.number(), latestOrderId: v.optional(v.string()), orderCount: v.number(), paidOrderCount: v.number() }).index("by_email", ["normalizedEmail"]).index("by_last_seen", ["lastSeenAt"]).searchIndex("search_name", { searchField: "name" }),
  journeyEvents: defineTable({ eventType: v.union(v.literal("landing"), v.literal("checkout_visit"), v.literal("checkout_submit"), v.literal("thankyou_visit")), visitorId: v.string(), experimentId: v.optional(v.string()), variant: v.optional(v.union(v.literal("AM"), v.literal("AM2"))), entryType: v.optional(v.union(v.literal("randomized"), v.literal("direct"), v.literal("test"))), attribution: v.optional(v.object(attributionFields)), dedupeKey: v.string(), occurredAt: v.number() }).index("by_dedupe_key", ["dedupeKey"]).index("by_visitor", ["visitorId", "occurredAt"]).index("by_occurred_at", ["occurredAt"]),
  reconciliationJobs: defineTable({ merchantOrderId: v.string(), kind: v.union(v.literal("status_check"), v.literal("receipt_match"), v.literal("reporting_retry")), status: v.union(v.literal("queued"), v.literal("running"), v.literal("completed"), v.literal("failed")), attempts: v.number(), nextRunAt: v.number(), lastError: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number() }).index("by_status_next_run", ["status", "nextRunAt"]).index("by_order", ["merchantOrderId", "updatedAt"]),
  paymentReceipts: defineTable({ merchantOrderId: v.string(), providerEventId: v.string(), state: v.string(), amountPaise: v.optional(v.number()), errorCode: v.optional(v.string()), errorMessage: v.optional(v.string()), receivedAt: v.number() }).index("by_provider_event", ["providerEventId"]).index("by_order", ["merchantOrderId", "receivedAt"]),
  reportingFailures: defineTable({ kind: v.union(v.literal("convex_write"), v.literal("make_delivery"), v.literal("payment_reconciliation")), referenceId: v.string(), message: v.string(), occurredAt: v.number(), resolvedAt: v.optional(v.number()) }).index("by_kind", ["kind", "occurredAt"]).index("by_reference", ["referenceId"]),
  dailyMetrics: defineTable({ experimentId: v.string(), day: v.string(), variant: v.union(v.literal("AM"), v.literal("AM2")), visitors: v.number(), purchasingVisitors: v.number(), paidOrders: v.number(), revenuePaise: v.number() }).index("by_experiment_day_variant", ["experimentId", "day", "variant"]),
  adminAudit: defineTable({ action: v.string(), actorUserId: v.string(), details: v.string(), occurredAt: v.number() }).index("by_occurred_at", ["occurredAt"]),
});
